to_do/budget/urls.py
from django.urls import path
from .views import *

app_name = 'budget'

urlpatterns = [
    path("",allprojects.as_view(),name='list'),
    path("<slug>/",detail.as_view(),name='detail'),
    path("expense/<str:slug>/",expense.as_view(),name='expense'),
    path("expense/update/<int:pk>/",updateexpense.as_view(),name="update_expense"),
    path("expense/delete/<int:pk>/",deleteexpense.as_view(),name="expense_delete"),
]

to_do/tasks/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("",Addtask.as_view(),name='home'),
    path("<int:pk>/",complete,name='completed'),
    path("search/",search,name='search')
]

to_do/to_do/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(('tasks.urls','tasks'),namespace='tasks')),
    path("accounts/",include(('accounts.urls','accounts'),namespace='accounts')),
    path("budget/",include(('budget.urls','budget'),namespace='budget')),
]

to_do/budget/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse_lazy,reverse

# Create your models here.
User = get_user_model()
class Project(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=50)
    description = models.TextField()
    budget_allocated = models.PositiveIntegerField()
    completion = models.DateField()

    def save(self,*args,**kwargs) -> None:
        self.slug = slugify(self.name)
        return super().save(*args,**kwargs)

    def __str__(self) -> str:
        return self.name

class Categories(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    add = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.add + "  --" + str(self.project)

class Expenses(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    expense = models.DecimalField(max_digits=10,decimal_places=3,default=0)
    # category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    name = models.CharField(max_length=225)

    def get_absolute_url(self):
        return reverse("budget:detail",kwargs={'slug':self.project.slug})

to_do/budget/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import *

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("name","description","budget_allocated")
        
        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields["name"].label = "Project Name"
            self.fields['description'].label = "Description"
            self.fields["budget_allocated"].label = "Budget"
            # self.fields["completion"].label = "Completion Date"

class ExpenseForm(forms.ModelForm):
    class Meta :
        model = Expenses
        fields = ("name","expense")      

to_do/budget/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView,UpdateView,DeleteView,DetailView,CreateView
from .models import *
from .forms import ProjectForm,ExpenseForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, request
from .utils import *
# Create your views here.

class allprojects(LoginRequiredMixin,CreateView):
    model = Project
    template_name = 'list.html'
    form_class = ProjectForm
    success_url = reverse_lazy("budget:list")

    def form_valid(self, form):
        form.instance.user =self.request.user
        form.instance.completion = self.request.POST['completion']
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        def multiple():
            list = []
            projects = Project.objects.filter(user=self.request.user)
            for project in projects:
                expenses = Expenses.objects.filter(project=project)
                remaining = total_remaining(project,expenses)
                list.append(remaining)
            return(list)

        all_projects = Project.objects.filter(user=self.request.user)
        budget_remaining = multiple()
        all = zip(all_projects,budget_remaining)
        context["all"] = all
        return context

class detail(LoginRequiredMixin,DetailView):
    model = Project
    context_object_name = 'project'
    template_name = 'detail.html'

    def get_object(self, *args,**kwargs):
        obj =  super().get_object(*args,**kwargs)
        if obj.user != self.request.user:
            raise PermissionDenied()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = get_object_or_404(Project,slug=self.kwargs["slug"])
        expenses = Expenses.objects.filter(project=project)
    
        context["expenses"] = Expenses.objects.filter(project=project)
        context["total_expense"] = total_expense(expenses)
        context["budget_remaining"] = total_remaining(project,expenses)
        return context

class expense(CreateView):
    model = Expenses
    form_class = ExpenseForm
    template_name = 'form.html'

    def form_valid(self, form,**kwargs):
        project = get_object_or_404(Project,slug=self.kwargs["slug"])
        form.instance.project = project
        # form.instance.name = form.cleaned_data["name"]
        # form.instance.expense = form.cleaned_data["cost"]
        form.save()
        return super().form_valid(form,**kwargs)

class updateexpense(UpdateView):
    model = Expenses
    form_class = ExpenseForm
    template_name = 'form.html'

    def get_object(self, *args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.project.user != self.request.user:
            raise PermissionDenied()
        return obj

class deleteexpense(DeleteView):
    model = Expenses

    def delete(self, request, *args, **kwargs):
        expense_id = Expenses.objects.get(id=self.kwargs["pk"])
        project_slug = expense_id.project.slug
        expense_id.delete()
        return HttpResponseRedirect(reverse("budget:detail",kwargs={"slug":project_slug}))

to_do/budget/templates/detail.html
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col" style="background-color: red;color:white;">
                <p>Project Name</p>
                <h3>{{project.name}}</h3>
            </div>
            <div class="col-sm-1">

            </div>
            <div class="col" style="background-color: blue;color:white;">
                <p>Budget</p>
                <h3>{{project.budget_allocated}}</h3>
            </div>
            <div class="col-sm-1">

            </div>
            <div class="col" style="background-color:slateblue;color:white;">
                <p>Remaining Amount</p>
                <h3>{{budget_remaining}}</h3>
            </div>
        </div>
    </div>
    <br><br>
    <a class="btn btn-primary" href="{% url 'budget:expense' project.slug %}" >Add Expense</a>
    <!-- Modal  data-target="#second" data-toggle="modal"  -->
    <!-- <div class="modal fade" id="second" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Expense</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'budget:expense' project.slug %}" method="post">
                        {% csrf_token %}
                        <label for="name">Expense Title : </label>
                        <input type="text" name="name" id="name"><br><br>
                        <label for="cost">Ammount : </label>
                        <input type="number" name="cost" id="cost" min="0"><br><br>
                        <input type="submit" value="Add" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>  -->
    <br><br><br><br>
    <h3>Project Description</h3>
    <p>{{project.description}}</p>
    <br><br><br><br>
    <h5>Completion Date : {{project.completion}}</h5>
    <br><br><br><br>
    <h3>All Expences </h3>
    <br><br>
    <table class="table table-dark">
        <thead>
            <tr>
                <td>Expense Name</td>
                <td>Amount Spent</td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% if expenses %}
                {% for exp in expenses %}
                    <tr>
                        <td>{{exp.name}}</td>
                        <td>{{exp.expense}}</td>
                        <td ><a href="{% url 'budget:update_expense' pk=exp.id %}">Update</a></td>
                        <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal{{exp.id}}" >Delete</button></td>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{exp.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Delete Expense</h5>
                                        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{% url 'budget:expense_delete' exp.id %}" method="post">
                                            {% csrf_token %}
                                            <h5>Are you sure you want to delete {{exp.name}}</h5>
                                            <input type="submit" value="Delete">
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </tr>
                {% endfor %}
            {% else %}
                <td>No Expenses registered</td>
            {% endif %}
        </tbody>
    </table>

    <h5>Total Expenses = {{total_expense}} </h5>

{% endblock %}

to_do/budget/templates/form.html
{% extends 'main.html' %}
{% load bootstrap4 %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Add Expense" class="btn btn-primary">
    </form>
    <!-- <form  method="post">
        {% csrf_token %}
        <label for="name">Expense name : </label>
        <input type="text" name="name" id="name"><br><br>
        <label for="cost">Cost :</label>
        <input type="number" name="cost" id="cost" min="0" ><br><br>
        <input type="submit" value="Add Expense" class="btn btn-primary">
    </form> -->
{% endblock %}

to_do/budget/templates/list.html
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block content %}
    <button class="btn btn-large btn-primary" style="margin: auto;" data-target="#second" data-toggle="modal">New Project</button>

    <!-- Modal -->
    <div class="modal fade" id="second" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Project</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <label for="completion">Completion Date : </label>
                        <input type="date" name="completion" id="completion"><br>
                        <input type="submit" value="Create" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div> 
    <br><br><br><br>
    {% if all %}
        <table class="table table-dark">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Budget</td>
                    <td>Ammount Remaining</td>
                </tr>
            </thead>
            <tbody>
                {% for project,remains in all %}
                    <tr>
                        <td><a href="{% url 'budget:detail' project.slug  %}">{{project.name}}</a></td>
                        <td>{{project.budget_allocated}}</td>
                            {% if remains < 0 %}
                                <td style="color: red;">
                                    <p>Over Budget</p>
                                    {{remains}}
                                </td>
                            {% else %}
                                <td>{{remains}}</td>
                            {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}